DROP TABLE IF EXISTS PERSON CASCADE;
CREATE TABLE IF NOT EXISTS PERSON
(
    PERSON_ID BIGSERIAL PRIMARY KEY,
    FULL_NAME VARCHAR (255),
    TITLE VARCHAR (255),
    AGE INTEGER
    );

DROP TABLE IF EXISTS BOOK;
CREATE TABLE IF NOT EXISTS BOOK
(
    BOOK_ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR (255),
    AUTHOR VARCHAR (255),
    PAGE_COUNT INTEGER,
    USER_ID BIGINT,
    CONSTRAINT person_fkey FOREIGN KEY (user_id)
    REFERENCES PERSON (person_id)
    );